/**
 * Type declarations for the RKSAVR class.
 * Mirrors `lib/rksavr.js` exports — generated by hand to track the public surface.
 */

export interface RKSAVRConfig {
  scaleA1?: number;
  scaleA2?: number;
  scales?: number[] | null;
  weights?: number[] | null;
  sampleSize?: number;
  iterations?: number;
  blockSize?: number;
  optimizerType?: 'brent' | 'nelder-mead' | 'annealing' | 'de' | 'ags';
  hMin?: number;
  hMax?: number;
  sampler?: ((data: number[], n: number) => number[]) | null;
  progress?: ((p: number) => void) | null;
}

export interface RollingResult {
  t: number;
  H: number;
}

export interface EstimateResult {
  H: number;
  minimizedD: number;
}

export interface SingleEstimate {
  H: number;
  minimizedD: number;
  significance?: {
    pValue: number;
    significant: boolean;
  };
  se?: number;
  ci?: {lower: number; upper: number};
}

export declare class RKSAVR {
  constructor(config?: RKSAVRConfig);
  estimate(data: number[]): number;
  estimateSingle(data: number[]): number;
  estimateSingleWithDiagnostics(data: number[]): SingleEstimate;
  rolling(
    data: number[],
    windowSize: number,
    step?: number,
    onProgress?: (p: number) => void,
  ): RollingResult[];
  rollingMultiScale(
    data: number[],
    windowSize: number,
    scales: number[],
    weights: number[],
    step?: number,
  ): RollingResult[];
  static getIncrements(data: number[], a: number): number[];
  _estimateSingleRaw(
    data: number[],
    opts: {scales?: number[]},
  ): {
    H: number;
    sortedSamples: number[][];
    scaleValues: number[];
  };
}
